name: "Release (auth independent)"

on:
    workflow_dispatch: # Allow manually running the action
    push:
        # Run when a tag matching the pattern "photos-v*"" is pushed
        # See: [Note: Testing release workflows that are triggered by tags]
        tags:
            - "auth-v*"

env:
    FLUTTER_VERSION: "3.24.3"

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: auth

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - name: Setup keys
              uses: timheuer/base64-to-file@v1
              with:
                  fileName: "keystore/ente_photos_key.jks"
                  encodedString: ${{ secrets.SIGNING_KEY_PHOTOS }}

            - name: Build independent APK
              run: |
                flutter build apk --dart-define=cronetHttpNoPlay=true --release --flavor independent
                mv build/app/outputs/flutter-apk/app-independent-release.apk build/app/outputs/flutter-apk/ente-auth-${{ github.ref_name }}.apk
              env:
                  SIGNING_KEY_PATH: "/home/runner/work/_temp/keystore/ente_photos_key.jks"
                  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS_PHOTOS }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD_PHOTOS }}
                  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD_PHOTOS }}

            - name: Checksum
              run: sha256sum build/app/outputs/flutter-apk/ente-auth-main.apk > build/app/outputs/flutter-apk/sha256sum

            - name: Upload outputs directory
              uses: actions/upload-artifact@main
              with:
                name: ente-photos-android
                path: auth/build/app/outputs/flutter-apk/

            - name: Generate release tag
              id: tag
              run: |
                echo "release_tag=$(date +"%Y.%m.%d-%H%M")">>$GITHUB_OUTPUT
                touch release.txt
                echo "status=success">>$GITHUB_OUTPUT

            - name: Upload firmware to release
              uses: softprops/action-gh-release@v2
              if: steps.tag.outputs.status == 'success' && !cancelled()
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.tag.outputs.release_tag }}
                body_path: auth/release.txt
                files: auth/build/app/outputs/flutter-apk/*

            - name: Remove old Releases
              uses: dev-drprasad/delete-older-releases@master
              with:
                keep_latest: 3
                delete_tags: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
